version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - db_network

  api:
    build: ../Api-Projeto-Integrador/.
    container_name: api_container
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - db_network
    environment:
      NODE_ENV: development
    command: npm run dev
    depends_on:
      - mysql

volumes:
  db_data:

networks:
  db_network:
